---
- name: "Copy install script"
  template: "src=pkg_control.py.j2 dest=/tmp/pkg_control.py"

- name: "Install Package Control"
  command: "python3 /tmp/pkg_control.py"

- name: "Add Packages"
  copy:
    src: "files/Package Control.sublime-settings"
    dest: "{{ sublime_user_dir }}/Packages/User/Package Control.sublime-settings"

- name: Add Flake8Lint user settings
  copy:
    src: files/Flake8Lint.sublime-settings
    dest: "{{ sublime_user_dir }}/Packages/User/Flake8Lint.sublime-settings"
