---
- name: "Copy install script"
  template: "src=pkg_control.py.j2 dest=/tmp/pkg_control.py"

- name: "Install Package Control"
  command: "python3 /tmp/install_subl_pkg.py"

- name: "Add Packages"
  copy:
    src: "files/Package Control.sublime-settings"
    dest: "{{ sublime_package_settings_dest }}"

- name: Add Flake8Lint user settings
  copy:
    src: files/Flake8Lint.sublime-settings
    dest: "{{ sublime_flake8_settings }}"
