---
- name: "Add Packages"
  copy:
    src: "files/Package Control.sublime-settings"
    dest: "{{ sublime_user_dir }}/Packages/User/Package Control.sublime-settings"
  tags: [never, post-install]

- name: Add Flake8Lint user settings
  copy:
    src: files/Flake8Lint.sublime-settings
    dest: "{{ sublime_user_dir }}/Packages/User/Flake8Lint.sublime-settings"
  tags: [never, post-install]
