---
- name: Append to bash_aliases
  blockinfile:
    path: "{{ home_dir }}/.bash_aliases"
    create: "yes"
    block: |
      alias cg='cd ~/src/git'

- name: Append more to bash_aliases just for Mac
  blockinfile:
    path: "{{ home_dir }}/.bash_aliases"
    block: |
      alias ll='ls -la'
  when: ansible_os_family == "Darwin"
