---
- name: "Add bash_profile"
  copy:
    src: files/bash_profile
    dest: "~/.bash_profile"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: "Add bash_aliases"
  copy:
    src: files/bash_aliases
    dest: "~/.bash_aliases"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create config directory
  file: "path=~/.config state=directory"

- name: "Add mupen64plus config"
  copy:
    src: files/mupen64plus.cfg
    dest: "~/.config/mupen64plus/mupen64plus.cfg"
