---
- name: Setup machine
  hosts: localhost
  vars:
    group: "{{ ansible_env.USER }}"
    home_dir: "{{ ansible_facts['user_dir'] }}"
    sublime_user_dir: "{{ ansible_facts['user_dir'] }}/.config/sublime-text"
  roles:
    - ubuntu
    - common
