---
- name: Setup machine
  hosts: localhost
  vars:
    group: "{{ ansible_env.USER }}"
    home_dir: "/home/{{ ansible_env.USER }}"
    sublime_user_dir: "/home/{{ ansible_env.USER }}/.config/sublime-text-3"
  roles:
    - ubuntu
    - common
