---
- name: "Install miscellaneous apt packages"
  apt: "pkg={{ item }} state=present update-cache=yes"
  with_items:
    - apt-transport-https
    - daemon
    - git
    - git-core
    - libpq-dev
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-gnutls-dev
    - libgnutls28-dev
    - python-dev
    - python3-dev
    - python3-gpg  # For dropbox. Use python-gpgme for 16.04 or lower.
    - nodejs
    - npm
    - keepass2
    - terminator
    - dropbox
    - kdiff3
    - vim
    - tree
    - ack
    - snapd
  become: "yes"

# Docker
- name: "Add repo key for docker-ce"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: "yes"

- name: "Add apt repo for docker-ce"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"  # bionic is for 18.04
  become: "yes"

- name: "Install docker-ce"
  apt: "pkg=docker-ce state=present update-cache=yes"
  become: "yes"

# yarn
- name: "Add repo key for yarn"
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
  become: "yes"

- name: "Add apt repo for yarn"
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
  become: "yes"

- name: "Install yarn"
  apt: "pkg=yarn state=present update-cache=yes install_recommends=no"
  become: "yes"

# Sublime
- name: "Add repo key for sublime-text"
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
  become: "yes"

- name: "Add apt repo for sublime-text"
  apt_repository:
    repo: "deb https://download.sublimetext.com/ apt/stable/"
  become: "yes"

- name: "Install sublime-text"
  apt: "pkg=sublime-text state=present update-cache=yes"
  become: "yes"

# Spotify
- name: "Add repo key for spotify"
  apt_key:
    url: https://download.spotify.com/debian/pubkey.gpg
  become: "yes"

- name: "Add apt repo for spotify"
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
  become: "yes"

- name: "Install spotify"
  apt: "pkg=spotify-client state=present update-cache=yes"
  become: "yes"
