---
- name: "Install miscellaneous apt packages"
  apt: "pkg={{ item }} state=present update-cache=yes"
  with_items:
    - apt-transport-https
    - daemon
    - git
    - git-core
    - libpq-dev
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-gnutls-dev
    - libgnutls28-dev
    - python-dev
    - python3-dev
    - python-gpgme
    - nodejs
    - npm
    - keepass2
    - chromium-browser
    - terminator
    - dropbox
    - kdiff3
    - vlc
  become: "yes"

- name: "Add repo key for docker-ce"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: "yes"

- name: "Add apt repo for docker-ce"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
  become: "yes"

- name: "Install docker-ce"
  apt: "pkg=docker-ce state=present update-cache=yes"
  become: "yes"

- name: "Add repo key for sublime-text"
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
  become: "yes"

- name: "Add apt repo for sublime-text"
  apt_repository:
    repo: "deb https://download.sublimetext.com/ apt/stable/"
  become: "yes"

- name: "Install sublime-text"
  apt: "pkg=sublime-text state=present update-cache=yes"
  become: "yes"

- name: "Add repo key for spotify"
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 0DF731E45CE24F27EEEB1450EFDC8610341D9410
  become: "yes"

- name: "Add apt repo for spotify"
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
  become: "yes"

- name: "Install spotify"
  apt: "pkg=spotify-client state=present update-cache=yes"
  become: "yes"
