---
- name: Make .ssh directory
  file:
    path: "/home/{{ ansible_env.USER }}/.ssh"
    state: directory
    mode: 0755

- name: Add ssh config
  copy:
    src: files/ssh_config
    dest: "/home/{{ ansible_env.USER }}/.ssh/config"

- name: Append to bashrc
  blockinfile:
    path: "/home/{{ ansible_env.USER }}/.bashrc"
    block: |
      export PATH=/home/{{ ansible_env.USER }}/.local/bin:/snap/bin:$PATH

      # Customize look of terminal
      RED="\[\033[0;31m\]"
      YELLOW="\[\033[0;33m\]"
      GREEN="\[\033[0;32m\]"
      NO_COLOR="\[\033[0m\]"
      WHITE="\[\e[01;37m\]"
      BLUE="\[\033[1;34m\]"

      #PS1='\[\033[0;32m\]\u\[\033[00m\] in \[\033[0;32m\]$( pwd ) ($( OUT=$( ls -A | wc -l ); echo $OUT ) entries, $(( $( ls -A | wc -l ) - $( ls | wc -l ) )) hidden)'

      function parse_git_branch () {
        git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
      }

      PS1="[$BLUE\u$WHITE@$BLUE${HOSTNAME%%.*}$WHITE]:\w$YELLOW\$(parse_git_branch)\$ \[\e[0m\]"
